name: Trigger Jenkins Job

on:
  workflow_dispatch:

jobs:
  trigger:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "${{ secrets.URL }}/job/${{ secrets.JOB }}/build" \
          --user "${{ secrets.USER }}:${{ secrets.TOKEN }}"
          echo "Jenkins Job Triggered"
